baseURL = 'https://jason.motylinski.com/'
title = 'Jason Motylinski'
languageCode = 'en-us'
theme = 'anatole'

[params]
author = 'Jason Motylinski'
description = 'Jason Motylinski'
profilePicture = 'images/me-work.png'
fullPostContent = true
displayMode = 'light'
disableThemeSwitcher = true
contentratio = 0.8
relatedPosts = true
numberOfRelatedPosts = 3

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/jasonmotylinski"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/jasonmotylinski"

[[params.socialIcons]]
icon = "fa-regular fa-envelope"
title = "E-mail"
url = "mailto:jason@motylinski.com?subject=Hello!"
target = "_self"

[[params.socialIcons]]
icon = "fa-regular fa-file-pdf"
title = "Resume"
url = "Jason Motylinski Resume.pdf"

[params.mermaid]
enable = true

[menus]
[[menus.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  pageRef = "/"

[[menus.main]]
  name = "Posts"
  identifier = "Posts"
  weight = 200
  pageRef= "/posts/"


[[menus.main]]
  name = "Projects"
  identifier = "projects"
  weight = 300
  pageRef= "/projects/"

[markup]
    defaultMarkdownHandler = 'goldmark'
    [markup.goldmark]
        [markup.goldmark.renderer]
            hardWraps = true
            unsafe = true
[services]
  [services.googleAnalytics]
    ID = 'G-N18DLRD200'
